const express = require('express');
const router = express.Router();
const sportsController = require("../controller/sportsController");

router.post("/get-all-markets", sportsController.getAllMarketAction);
router.post("/get-all-matches", sportsController.getAllMatchAction);
router.post("/get-all-league", sportsController.getAllLeagueAction);
router.post("/get-all-sport", sportsController.getAllSportAction);
router.post("/get-league", sportsController.getLeagueAction);
router.post("/get-match", sportsController.getMatchAction);
router.post("/get-live", sportsController.getLiveAction);
router.post("/get-event", sportsController.getEventAction);
router.post("/get-today-match", sportsController.getTodayMatchAction);
// router.post("/get-result", sportsController.getResultAction);
router.post("/user-bet", sportsController.userBetAction);
router.post("/bet-history", sportsController.getHistoryAction);
router.post("/set-result", sportsController.setResultAction);
router.post("/set-live-result", sportsController.setLiveResultAction);
router.post("/get-favorite", sportsController.getFavoriteAction);
router.post("/save-favorite", sportsController.saveFavoriteAction);
router.post("/clear", sportsController.clear);
module.exports = router;